// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDskGybfwROO0HbQY-Dq73Irz2CLjyIrIw',
    appId: '1:955359163880:web:457b6c689b74ac0eb4a05d',
    messagingSenderId: '955359163880',
    projectId: 'e-commerce-2d404',
    authDomain: 'e-commerce-2d404.firebaseapp.com',
    storageBucket: 'e-commerce-2d404.firebasestorage.app',
    measurementId: 'G-72ENGTT052',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxgd9_Jxjafu3fosKZTERxb5p1Xd0p_GQ',
    appId: '1:955359163880:android:11f4dc52ec193d0ab4a05d',
    messagingSenderId: '955359163880',
    projectId: 'e-commerce-2d404',
    storageBucket: 'e-commerce-2d404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtkgJwFwCEYB3DFptD2H5UGut_JzzGZfM',
    appId: '1:955359163880:ios:6887ce281baea5f5b4a05d',
    messagingSenderId: '955359163880',
    projectId: 'e-commerce-2d404',
    storageBucket: 'e-commerce-2d404.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtkgJwFwCEYB3DFptD2H5UGut_JzzGZfM',
    appId: '1:955359163880:ios:6887ce281baea5f5b4a05d',
    messagingSenderId: '955359163880',
    projectId: 'e-commerce-2d404',
    storageBucket: 'e-commerce-2d404.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDskGybfwROO0HbQY-Dq73Irz2CLjyIrIw',
    appId: '1:955359163880:web:592503474aff5903b4a05d',
    messagingSenderId: '955359163880',
    projectId: 'e-commerce-2d404',
    authDomain: 'e-commerce-2d404.firebaseapp.com',
    storageBucket: 'e-commerce-2d404.firebasestorage.app',
    measurementId: 'G-887Z52JTSX',
  );
}
